def daily_sales_report(orders: list) -> dict: ...
def top_selling_items(orders: list, menu: dict, limit: int = 5) -> list:...
def server_performance(orders: list) -> dict: ...
def export_report(report: dict, filename: str) -> str: ...
